#ifndef _ARDISCOVERY_ERROR_H_
#define _ARDISCOVERY_ERROR_H_

/**
 * @brief libARDiscovery errors known.
 */
typedef enum
{
    ARDISCOVERY_OK = 0,
    ARDISCOVERY_ERROR = -1,

    ARDISCOVERY_ERROR_SIMPLE_POLL = -1000, /* Avahi related */
    ARDISCOVERY_ERROR_BUILD_NAME,
    ARDISCOVERY_ERROR_CLIENT,
    ARDISCOVERY_ERROR_SERVICE_CREATION,
    ARDISCOVERY_ERROR_ENTRY_GROUP,
    ARDISCOVERY_ERROR_ADD_SERVICE,
    ARDISCOVERY_ERROR_GROUP_COMMIT,

    ARDISCOVERY_ERROR_PORT = -2000, /* Connection related */
    ARDISCOVERY_ERROR_CONNECT,
    ARDISCOVERY_ERROR_ALLOC,
    ARDISCOVERY_ERROR_SOCKET_CREATION,
    ARDISCOVERY_ERROR_SOCKET_PERMISSION_DENIED,
    ARDISCOVERY_ERROR_SOCKET_ALREADY_CONNECTED,
    ARDISCOVERY_ERROR_ACCEPT,

    ARDISCOVERY_ERROR_CALLBACK = -3000, /* Processing related */
    ARDISCOVERY_ERROR_JSON_PARSE,
    ARDISCOVERY_ERROR_JSON_VALUE,

} eARDISCOVERY_ERROR;

#endif /* _ARDISCOVERY_ERROR_H_ */
